"""
Seed the prerequisite edges for the physics-9 and physics-10 roadmaps.

Authored as  title -> [prerequisite titles]  (stable key = title; node UUIDs are
regenerated by seed_physics_school.py). 132 same-class edges, transitive reduction,
DAG-verified per roadmap.

Split 2026-07-17 (docs/SPEC-school-science-viz.md, D-029) from the original single
physics-9-10 roadmap's 140-edge graph. The roadmaps API resolves prerequisites/unlocks
by looking up node IDs strictly within the ONE roadmap being requested
(`RoadmapNodePrerequisite.node_id.in_(node_ids)` in backend/app/api/routes/roadmaps.py) —
it has no notion of a cross-roadmap edge, so the 8 Class 9 -> Class 10 edges from the
original graph are DROPPED here rather than silently producing a prerequisite the
frontend can't resolve (a node ID with no title/status in the requesting roadmap's own
node list). They are kept below, commented out, as the record of what was lost and as
the input to a future cross-roadmap "why am I stuck" feature if one gets built:

    Rearrange linear algebraic equations   -> Cross-multiplication in proportions
    Read coordinates from a line graph     -> Sign convention for coordinates
    Apply average speed formula            -> Relate refractive index to speed of light
    Define work done by a constant force   -> Define electric potential difference
    Rearrange linear algebraic equations   -> Apply Ohm's law to circuits
    Rearrange linear algebraic equations   -> Apply resistivity formula
    Apply power formula                    -> Apply electric power formulas
    Apply F = ma                           -> Identify conditions for magnetic force

Idempotent: clears each roadmap's edges first, then re-inserts.
Run AFTER seed_physics_school.py:
    ./.venv/Scripts/python.exe seed_physics_school_prereqs.py
"""
import asyncio
import uuid
from sqlalchemy import text
from app.core.database import engine

PHYSICS_9_ID = uuid.UUID("f9f9f9f9-f9f9-f9f9-f9f9-f9f9f9f9f9f9")
PHYSICS_10_ID = uuid.UUID("f1f1f1f1-f1f1-f1f1-f1f1-f1f1f1f1f1f1")

# node title -> the titles that should be understood BEFORE it.
# Titles must match seed_physics_school.py exactly (verified by the missing-title check below).
# Every edge here is same-class by construction (the 8 cross-year edges are dropped — see docstring).
PREREQS_9 = {
    # ---------------- Class 9 · Motion ----------------
    "Calculate the slope of a straight line": ["Read coordinates from a line graph"],
    "Define displacement": ["Define distance"],
    "Distinguish distance from displacement": ["Define displacement"],
    "Determine if displacement is zero": ["Define displacement"],
    "Apply average speed formula": ["Define average speed", "Rearrange linear algebraic equations"],
    "Distinguish speed from velocity": ["Define velocity", "Define average speed", "Distinguish distance from displacement"],
    "Calculate average velocity": ["Define velocity"],
    "Distinguish uniform and non-uniform acceleration": ["Define acceleration"],
    "Apply acceleration formula": ["Define acceleration", "Rearrange linear algebraic equations"],
    "Interpret sign of acceleration": ["Define acceleration"],
    "Interpret uniform motion on distance-time graph": ["Interpret stationary object on distance-time graph"],
    "Read speed off a distance-time graph": ["Calculate the slope of a straight line", "Interpret uniform motion on distance-time graph"],
    "Interpret uniform acceleration on velocity-time graph": ["Interpret uniform velocity on velocity-time graph"],
    "Read acceleration off a velocity-time graph": ["Calculate the slope of a straight line", "Interpret uniform acceleration on velocity-time graph"],
    "Read displacement off a velocity-time graph": ["Calculate area of triangle and rectangle", "Define displacement"],
    "Apply v = u + at": ["Define acceleration", "Rearrange linear algebraic equations"],
    "Apply s = ut + 1/2 at^2": ["Define acceleration", "Rearrange linear algebraic equations"],
    "Apply 2as = v^2 - u^2": ["Define acceleration", "Rearrange linear algebraic equations"],
    "Select correct equation of motion": ["Apply v = u + at", "Apply s = ut + 1/2 at^2", "Apply 2as = v^2 - u^2"],
    "Identify uniform circular motion as accelerated": ["Define acceleration"],
    "Calculate speed in circular motion": ["Apply average speed formula"],
    "Define average speed": ["Define distance"],
    "Define velocity": ["Define displacement"],
    "Define acceleration": ["Define velocity"],

    # ---------------- Class 9 · Force and Laws of Motion ----------------
    "State Newton's first law of motion": ["Distinguish balanced and unbalanced forces"],
    "Define inertia": ["State Newton's first law of motion"],
    "Relate inertia to mass": ["Define inertia"],
    "Define momentum": ["Define velocity"],
    "State Newton's second law of motion": ["Define momentum", "Define acceleration"],
    "Apply F = ma": ["State Newton's second law of motion", "Rearrange linear algebraic equations"],
    "Identify action-reaction pairs": ["State Newton's third law of motion", "Distinguish balanced and unbalanced forces"],

    # ---------------- Class 9 · Gravitation ----------------
    "Apply F = G m1 m2 / r^2": ["State the universal law of gravitation", "Rearrange linear algebraic equations"],
    "State acceleration due to gravity (g)": ["Define free fall", "Define acceleration"],
    "Apply equations of motion for free fall": ["Apply v = u + at", "Apply s = ut + 1/2 at^2", "Apply 2as = v^2 - u^2", "State acceleration due to gravity (g)"],
    "Distinguish mass and weight": ["Relate inertia to mass", "Apply F = ma"],
    "Calculate weight on earth and moon": ["Distinguish mass and weight"],
    "Define pressure": ["Define thrust"],
    "Apply Pressure = Force / Area": ["Define pressure", "Rearrange linear algebraic equations"],
    "Determine if an object floats or sinks": ["Define buoyant force"],
    "State Archimedes principle": ["Define buoyant force"],

    # ---------------- Class 9 · Work and Energy ----------------
    "Identify zero work conditions": ["Define work done by a constant force", "Determine if displacement is zero"],
    "Interpret negative work": ["Define work done by a constant force"],
    "Apply kinetic energy formula": ["Define energy", "Rearrange linear algebraic equations"],
    "Relate work to change in kinetic energy": ["Apply kinetic energy formula", "Define work done by a constant force", "Apply 2as = v^2 - u^2"],
    "Apply potential energy formula": ["Define gravitational potential energy", "Rearrange linear algebraic equations"],
    "Calculate mechanical energy of free falling object": ["State law of conservation of energy", "Apply potential energy formula", "Apply kinetic energy formula"],
    "Apply power formula": ["Define power", "Rearrange linear algebraic equations"],
    "Convert commercial unit of energy": ["Apply power formula"],

    # ---------------- Class 9 · Sound ----------------
    "Distinguish longitudinal and transverse waves": ["Identify sound as a mechanical wave"],
    "Apply wave speed equation": ["Define frequency, time period, and wavelength", "Rearrange linear algebraic equations"],
    "Relate pitch to frequency": ["Define frequency, time period, and wavelength"],
    "Relate loudness to amplitude": ["Define frequency, time period, and wavelength"],
    "Calculate distance using echo": ["State laws of reflection of sound", "Apply average speed formula"],
    "Describe applications of multiple reflections of sound": ["State laws of reflection of sound"],
}

PREREQS_10 = {
    # ---------------- Class 10 · Light ----------------
    "Define principal focus and focal length": ["Identify concave and convex mirrors"],
    "Draw ray diagrams for concave mirrors (real images)": ["Define principal focus and focal length"],
    "Draw ray diagrams for concave mirrors (virtual image)": ["Define principal focus and focal length"],
    "Draw ray diagrams for convex mirrors": ["Define principal focus and focal length"],
    "Apply mirror sign convention": ["Sign convention for coordinates", "Define principal focus and focal length"],
    "Apply mirror formula": ["Apply mirror sign convention", "Cross-multiplication in proportions"],
    "Calculate linear magnification (mirrors)": ["Apply mirror formula"],
    "Apply laws of refraction (Snell's Law)": ["Identify cause of refraction"],
    "Relate refractive index to speed of light": ["Identify cause of refraction"],
    "Apply relative refractive index": ["Relate refractive index to speed of light"],
    "Predict bending of light": ["Identify cause of refraction"],
    "Draw ray diagrams for convex lenses": ["Identify convex and concave lenses"],
    "Apply lens sign convention": ["Sign convention for coordinates", "Identify convex and concave lenses"],
    "Apply lens formula": ["Apply lens sign convention", "Cross-multiplication in proportions"],
    "Calculate linear magnification (lenses)": ["Apply lens formula"],
    "Calculate power of a lens": ["Apply lens formula"],

    # ---------------- Class 10 · Eye ----------------
    "Calculate power for vision correction": ["Identify myopia (near-sightedness)", "Identify hypermetropia (far-sightedness)", "Calculate power of a lens"],
    "Describe dispersion of white light": ["Predict bending of light"],
    "Explain twinkling of stars": ["Predict bending of light"],

    # ---------------- Class 10 · Electricity ----------------
    "Identify conventional current direction": ["Define electric current"],
    "State Ohm's Law": ["Define electric current", "Define electric potential difference"],
    "Apply Ohm's law to circuits": ["State Ohm's Law"],
    "Apply resistivity formula": ["Identify factors affecting resistance"],
    "Calculate equivalent resistance in series": ["Apply Ohm's law to circuits"],
    "Calculate equivalent resistance in parallel": ["Apply Ohm's law to circuits", "Calculate inverse sums"],
    "Solve complex resistor networks": ["Calculate equivalent resistance in series", "Calculate equivalent resistance in parallel"],
    "Calculate heat generated by current": ["Apply Ohm's law to circuits"],
    "Apply electric power formulas": ["Calculate heat generated by current"],

    # ---------------- Class 10 · Magnetic Effects ----------------
    "Apply Right-Hand Thumb Rule": ["Describe magnetic field lines", "Identify conventional current direction"],
    "Describe field of a solenoid": ["Apply Right-Hand Thumb Rule"],
    "Describe magnetic field of a circular loop": ["Apply Right-Hand Thumb Rule"],
    "Identify conditions for magnetic force": ["Describe magnetic field lines", "Identify conventional current direction"],
    "Apply Fleming's Left-Hand Rule": ["Identify conditions for magnetic force"],
    "Explain role of a fuse": ["Calculate heat generated by current", "Distinguish live, neutral, and earth wires"],
}

ROADMAPS = {"9": (PHYSICS_9_ID, PREREQS_9), "10": (PHYSICS_10_ID, PREREQS_10)}


async def _seed_one(conn, roadmap_id, prereqs):
    rows = (
        await conn.execute(
            text("SELECT id, title FROM roadmap_nodes WHERE roadmap_id = :rid"),
            {"rid": str(roadmap_id)},
        )
    ).all()
    id_by_title = {title: nid for nid, title in rows}
    if not id_by_title:
        print(f"No nodes found for roadmap {roadmap_id}. Run seed_physics_school.py first.")
        return 0, set()

    await conn.execute(
        text(
            "DELETE FROM roadmap_node_prerequisites WHERE node_id IN "
            "(SELECT id FROM roadmap_nodes WHERE roadmap_id = :rid)"
        ),
        {"rid": str(roadmap_id)},
    )

    inserted = 0
    missing = set()
    for title, prereq_titles in prereqs.items():
        nid = id_by_title.get(title)
        if nid is None:
            missing.add(title)
            continue
        for pt in prereq_titles:
            pid = id_by_title.get(pt)
            if pid is None:
                missing.add(pt)
                continue
            await conn.execute(
                text("INSERT INTO roadmap_node_prerequisites (id, node_id, prerequisite_node_id) "
                     "VALUES (:id, :nid, :pid)"),
                {"id": str(uuid.uuid4()), "nid": str(nid), "pid": str(pid)},
            )
            inserted += 1
    return inserted, missing


async def main():
    async with engine.begin() as conn:
        total_inserted = 0
        all_missing = set()
        for cls, (roadmap_id, prereqs) in ROADMAPS.items():
            inserted, missing = await _seed_one(conn, roadmap_id, prereqs)
            print(f"physics-{cls}: inserted {inserted} prerequisite edges.")
            total_inserted += inserted
            all_missing |= missing

    if all_missing:
        print(f"WARNING — titles not found in roadmap_nodes: {sorted(all_missing)}")
    print(f"Total: {total_inserted} prerequisite edges across physics-9 + physics-10.")


if __name__ == "__main__":
    asyncio.run(main())
