"""add paid_only to problems

Revision ID: 37714df921df
Revises: 37714df921de
Create Date: 2026-07-22 00:09:05.371619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '37714df921df'
down_revision: Union[str, Sequence[str], None] = '37714df921de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problems', sa.Column('paid_only', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('problems', 'paid_only')
    # ### end Alembic commands ###
