"""Add key_memory and mistake

Revision ID: b72bc0cf122c
Revises: c71d8f31ee19
Create Date: 2026-06-01 20:10:18.634660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b72bc0cf122c'
down_revision: Union[str, Sequence[str], None] = 'c71d8f31ee19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('key_memory', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('activities', sa.Column('mistake', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activities', 'mistake')
    op.drop_column('activities', 'key_memory')
    # ### end Alembic commands ###
